import os
import time
import random
from brain import MayaBrain
from media import MayaMedia
from social import MayaSocial
from agency import AgencyCOO

import json
from dotenv import load_dotenv

load_dotenv()
if not os.getenv("GEMINI_API_KEY"):
    load_dotenv(os.path.join(os.path.dirname(__file__), "..", ".env"))

class MayaAutopilot:
    def __init__(self):
        print("Initializing Maya Autopilot...")
        self.brain = MayaBrain()
        self.media = MayaMedia()
        self.social = MayaSocial()
        self.agency = AgencyCOO()

        # Use /tmp for serverless environments
        self.tmp_dir = "/tmp" if os.environ.get("VERCEL") else "."
        self.state_file = os.path.join(self.tmp_dir, "state.json")
        self.locations = ["Mumbai", "Milan", "Tuscany", "Goa"]

        # Load state from file if it exists, otherwise default
        self.state = {"current_location": "Mumbai"}
        self._load_state()

    def _load_state(self):
        if os.path.exists(self.state_file):
            try:
                with open(self.state_file, 'r') as f:
                    self.state = json.load(f)
                print(f"Loaded previous state. Location: {self.state.get('current_location')}")
            except Exception as e:
                print(f"Error loading state: {e}")

    def _save_state(self):
        try:
            with open(self.state_file, 'w') as f:
                json.dump(self.state, f)
            print("Successfully saved state.")
        except Exception as e:
            print(f"Error saving state: {e}")

    def run_cycle(self, post_type="photo", force_location=None):
        """
        Runs one complete generation and posting cycle.
        """
        location = force_location if force_location else self.state.get("current_location", "Mumbai")
        print(f"\n--- Starting Autopilot Cycle ---")
        print(f"Location: {location} | Type: {post_type}")

        if post_type == "photo":
            # 1. BRAIN: Generate Concept
            print("\n[1/4] Brain generating Photo concept...")
            post_data = self.brain.generate_post(location=location, post_type=post_type)
            print(f"Prompt Generated: {post_data['image_prompt'][:100]}...")
            print(f"Caption Generated: {post_data['caption'][:50]}...")

            # 2. MEDIA: Generate Asset
            print("\n[2/4] Media generating visual assets...")
            upload_path = os.path.join(self.tmp_dir, "maya_temp.jpg")
            max_retries = 3
            image_verified = False

            for attempt in range(1, max_retries + 1):
                print(f"--- Image Generation Attempt {attempt}/{max_retries} ---")
                self.media.generate_image(post_data["image_prompt"], output_path=upload_path)

                # Verify the image quality with the Brain
                if self.brain.verify_image(upload_path):
                    image_verified = True
                    break
                else:
                    print("Discarding image and retrying...")

            if not image_verified:
                print("Warning: Max retries reached. Proceeding with the final generated image anyway.")

            # Add the Viral Text Overlay
            self.media.add_viral_text_to_image(upload_path, post_data["viral_hook_text"])
            caption_to_post = post_data["caption"]

        elif post_type == "reel":
            # 1. AGENCY: Multi-Agent Storyboarding for Reels
            print("\n[1/4] Agency Ecosystem generating Cinematic Reel Storyboard...")
            concept = f"Luxury Travel & Fashion fusion concept set in {location}."

            # Run the multi-agent debate to get the final storyboard and SEO metadata
            agency_output = self.agency.run_reel_workflow(concept)

            upload_path = os.path.join(self.tmp_dir, "maya_temp.mp4")
            print("\n[2/4] Requesting True Cinematic Video via Muapi...")

            # Extract the actual storyboard to use as the video prompt
            storyboard_prompt = agency_output.get("storyboard", "")

            # Construct a prompt for Muapi using the strict storyboard generated by the Creative Director
            # Face anchoring is added to maintain persona
            video_prompt = f"Highly realistic cinematic footage set in {location}. Face is a 50/50 blend of Monica Bellucci and Deepika Padukone. {storyboard_prompt}"
            self.media.generate_video(video_prompt, output_path=upload_path)

            # Extract the generated caption
            metadata = agency_output.get("metadata", "")
            parsed_caption = ""
            for line in metadata.split('\n'):
                if line.startswith("CAPTION:"):
                    parsed_caption = line.replace("CAPTION:", "").strip()
                    break

            if parsed_caption:
                caption_to_post = f"{parsed_caption}\n\n#VirtualInfluencer #MayasCrew"
            else:
                caption_to_post = f"Maya's Crew ✨ Location: {location}. #VirtualInfluencer\n(Scripted by Maya's Elite AI Agency)"

        # 3. SOCIAL: Post to Instagram
        print("\n[3/4] Logging into Instagram...")
        self.social.login()

        print(f"\n[4/4] Publishing {post_type}...")
        if post_type == "photo":
            self.social.post_photo(upload_path, caption_to_post)
        elif post_type == "reel":
            self.social.post_reel(upload_path, caption_to_post)

        # Cleanup temp files
        print("\nCleaning up temporary files...")
        jpg_path = os.path.join(self.tmp_dir, "maya_temp.jpg")
        mp4_path = os.path.join(self.tmp_dir, "maya_temp.mp4")
        if os.path.exists(jpg_path):
            os.remove(jpg_path)
        if os.path.exists(mp4_path):
            os.remove(mp4_path)

        # Save state at the very end
        self._save_state()

        print("--- Autopilot Cycle Complete ---\n")

    def travel(self):
        """Randomly decides to travel to a new location."""
        current = self.state.get("current_location", "Mumbai")
        new_location = random.choice([loc for loc in self.locations if loc != current])
        print(f"Maya is traveling from {current} to {new_location} ✈️")
        self.state["current_location"] = new_location
        self._save_state()

if __name__ == "__main__":
    autopilot = MayaAutopilot()

    print("Welcome to Maya Rossi's True Autopilot.")
    print("Checking environment variables and initiating cycle...")

    # Choose randomly between a photo and a reel for variety
    post_choice = random.choice(["photo", "photo", "reel"])

    try:
        # Occasionally travel to keep the content dynamic
        if random.random() < 0.2: # 20% chance to travel
            autopilot.travel()

        autopilot.run_cycle(post_type=post_choice)
    except Exception as e:
        print(f"Autopilot encountered a critical error during execution: {e}")
        # In a CI/CD environment like GitHub actions, we want it to exit with an error code
        # so you get an email notification if it fails.
        import sys
        sys.exit(1)
